FROM aaftio/face_recognition

ENV APP_ROOT /opt/attendance-monitoring-system
ENV PATH $APP_ROOT/python_env/bin:$PATH

COPY src ${APP_ROOT}
COPY requirements.txt server.py ${APP_ROOT}/

WORKDIR /opt/attendance-monitoring-system

CMD ["python3", "server.py"]