FROM aaftio/face_recognition

# Install dependencies
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install --upgrade pip

ENV APP_ROOT /opt/attendance-monitoring-system
ENV PATH $APP_ROOT/python_env/bin:$PATH

COPY src ${APP_ROOT}
COPY requirements.txt server.py ${APP_ROOT}/

RUN apt-get update

WORKDIR /opt/attendance-monitoring-system

RUN pip3 install flask
RUN pip3 install imutils
RUN pip3 install scipy
RUN pip3 install openpyxl

CMD ["python3", "server.py"]